-- =========================================================================
-- BBDU Grievance Portal — Production Supabase PostgreSQL Schema DDL Script
-- Copy and paste this script directly into Supabase SQL Editor to initialize.
-- =========================================================================

-- Enable UUID Extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -------------------------------------------------------------------------
-- 1. Custom User Table (accounts_customuser)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.accounts_customuser (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamp with time zone NULL,
    is_superuser boolean NOT NULL DEFAULT FALSE,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT FALSE,
    is_active boolean NOT NULL DEFAULT TRUE,
    date_joined timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role varchar(20) NOT NULL DEFAULT 'STUDENT',
    enrollment_no varchar(50) NULL,
    department varchar(50) NULL,
    phone_number varchar(15) NULL,
    CONSTRAINT check_role CHECK (role IN ('STUDENT', 'STAFF', 'ADMIN')),
    CONSTRAINT check_department CHECK (department IN ('Faculty / Teaching', 'Examination', 'Administration', 'Infrastructure', 'Hostel / Accommodation', 'Other') OR department IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_customuser_username ON public.accounts_customuser (username);
CREATE INDEX IF NOT EXISTS idx_customuser_email ON public.accounts_customuser (email);
CREATE INDEX IF NOT EXISTS idx_customuser_role ON public.accounts_customuser (role);

-- -------------------------------------------------------------------------
-- 2. Complaint Table (complaints_complaint)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.complaints_complaint (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id varchar(30) NOT NULL UNIQUE,
    category varchar(50) NOT NULL,
    department varchar(50) NOT NULL DEFAULT 'Faculty / Teaching',
    priority varchar(20) NOT NULL DEFAULT 'Medium',
    subject varchar(150) NOT NULL,
    description text NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Submitted',
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id bigint NOT NULL REFERENCES public.accounts_customuser(id) ON DELETE CASCADE,
    assigned_staff_id bigint NULL REFERENCES public.accounts_customuser(id) ON DELETE SET NULL,
    CONSTRAINT check_category CHECK (category IN ('Faculty / Teaching', 'Examination', 'Administration', 'Infrastructure', 'Hostel / Accommodation', 'Other')),
    CONSTRAINT check_priority CHECK (priority IN ('Low', 'Medium', 'High')),
    CONSTRAINT check_status CHECK (status IN ('Submitted', 'Under Review', 'In Progress', 'Resolved', 'Rejected', 'Closed'))
);

CREATE INDEX IF NOT EXISTS idx_complaint_complaint_id ON public.complaints_complaint (complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_student_id ON public.complaints_complaint (student_id);
CREATE INDEX IF NOT EXISTS idx_complaint_status ON public.complaints_complaint (status);
CREATE INDEX IF NOT EXISTS idx_complaint_category ON public.complaints_complaint (category);

-- -------------------------------------------------------------------------
-- 3. Complaint Audit Log Table (complaints_complaintstatuslog)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.complaints_complaintstatuslog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_status varchar(30) NOT NULL,
    new_status varchar(30) NOT NULL,
    remark text NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by_id bigint NOT NULL REFERENCES public.accounts_customuser(id) ON DELETE CASCADE,
    complaint_id bigint NOT NULL REFERENCES public.complaints_complaint(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_statuslog_complaint_id ON public.complaints_complaintstatuslog (complaint_id);

-- -------------------------------------------------------------------------
-- 4. Complaint Attachment Table (complaints_complaintattachment)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.complaints_complaintattachment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file varchar(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complaint_id bigint NOT NULL REFERENCES public.complaints_complaint(id) ON DELETE CASCADE
);

-- -------------------------------------------------------------------------
-- 5. Resolution Feedback Table (complaints_feedback)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.complaints_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complaint_id bigint NOT NULL UNIQUE REFERENCES public.complaints_complaint(id) ON DELETE CASCADE
);

-- =========================================================================
-- Row Level Security (RLS) Policies for Supabase (Optional Enhancement)
-- =========================================================================

ALTER TABLE public.accounts_customuser ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints_complaint ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints_complaintstatuslog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints_feedback ENABLE ROW LEVEL SECURITY;

-- Allow public read access to active tables (Service Role handles full CRUD)
CREATE POLICY "Allow public read access to complaints" ON public.complaints_complaint FOR SELECT USING (true);
CREATE POLICY "Allow student write to complaints" ON public.complaints_complaint FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read to user profiles" ON public.accounts_customuser FOR SELECT USING (true);

-- Done! Schema definition ready for BBDU Grievance Portal.
