# Generated by Django 6.1 on 2026-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('School of Engineering', 'School of Engineering'), ('School of Management', 'School of Management'), ('School of Computer Applications', 'School of Computer Applications'), ('School of Pharmacy', 'School of Pharmacy'), ('School of Allied Health Sciences', 'School of Allied Health Sciences'), ('School of Hotel Management', 'School of Hotel Management'), ('School of Architecture', 'School of Architecture'), ('School of Mass Communication', 'School of Mass Communication'), ('School of Legal Studies', 'School of Legal Studies'), ('School of Basic Sciences', 'School of Basic Sciences'), ('School of Education', 'School of Education'), ('Other / Administration', 'Other / Administration')], max_length=50, null=True),
        ),
    ]
