# Generated by Django 6.1 on 2026-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('Faculty / Teaching', 'Faculty / Teaching'), ('Examination', 'Examination'), ('Administration', 'Administration'), ('Infrastructure', 'Infrastructure'), ('Hostel / Accommodation', 'Hostel / Accommodation'), ('Other', 'Other')], default='Faculty / Teaching', help_text='Target Department for grievance processing', max_length=50),
        ),
    ]
